# Generated by Django 3.2.7 on 2021-09-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fossil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=200)),
                ('ut_catalog_id', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('age', models.DateField(verbose_name='age')),
            ],
        ),
    ]
