# Generated by Django 3.2.7 on 2021-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossil',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='scientific_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='site',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='ut_catalog_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
