# Generated by Django 3.2.7 on 2021-09-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0003_alter_fossil_ut_catalog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
