# Generated by Django 3.2.7 on 2021-09-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0004_fossil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
