# Generated by Django 3.2.7 on 2021-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0005_fossil_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=200)),
                ('ut_catalog_id', models.CharField(blank=True, max_length=200, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.AlterField(
            model_name='fossil',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fossil',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
