# Generated by Django 3.2.7 on 2021-10-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0007_auto_20210930_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fossil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/fossil'),
        ),
        migrations.AlterField(
            model_name='primate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/fossil'),
        ),
    ]
