# Generated by Django 3.2.7 on 2021-10-01 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0008_auto_20211001_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/fossil', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True)),
                ('default_image', models.BooleanField(default=False)),
                ('fossil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casts.fossil')),
            ],
        ),
    ]
