# Generated by Django 3.2.7 on 2021-10-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0009_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
