# Generated by Django 3.2.7 on 2021-10-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0011_auto_20211004_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images/origins', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True)),
                ('default_image', models.BooleanField(default=False)),
                ('fossil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='casts.fossil')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'managed': True,
            },
        ),
    ]
