# Generated by Django 3.2.7 on 2021-10-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0014_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='primate',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
