# Generated by Django 3.2.7 on 2021-10-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0015_auto_20211006_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='fossil',
            name='is_type_specimen',
            field=models.BooleanField(default=False, verbose_name='Type Specimen'),
        ),
    ]
