# Generated by Django 3.2.7 on 2021-09-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
